apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-install-openshift-oadp
placementBindingDefaults:
  name: openshift-oadp-operator-binding
policyDefaults:
  placement:
    placementRuleName: ocp-placementrule
  controls:
    - "CM-2 Baseline Configuration"
  pruneObjectBehavior: "DeleteIfCreated"
  namespace: global-policies
  remediationAction: enforce
  severity: medium
policies:
  - name: policy-ocp-oadp-operator
    manifests:
      - path: ./manifests
