kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-backup-sample2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
  #Storage class is left out. We expect there will be a default storage class that is CSI compliant
  #storageClassName: gp2
  