apiVersion: velero.io/v1
kind: Restore
metadata:
  name: backup-sample2-restore
  namespace: openshift-adp
spec:
  backupName: backup-sample2
  excludedResources:
    - nodes
    - events
    - events.events.k8s.io
    - backups.velero.io
    - restores.velero.io
    - resticrepositories.velero.io
  hooks: {}
  includedNamespaces:
    - '*'
  restorePVs: true