kind: Deployment
apiVersion: apps/v1
metadata:
  name: backup-sample1
  namespace: default
  labels:
    app: backup-sample1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-sample1
  template:
    metadata:
      labels:
        app: backup-sample1
    spec:
      containers:
        - resources: {}
          name: container
          command:
            - /bin/bash
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          args:
            - '-c'
            - 'while :;do sleep infinity;done'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
