kind: Secret
apiVersion: v1
metadata:
  name: odf-bucket-credential
  namespace: openshift-adp
stringData:
  cloud: |-
    [default]
    aws_access_key_id={{ fromSecret "openshift-adp" "oadp-bucket" "AWS_ACCESS_KEY_ID" | base64dec }}
    aws_secret_access_key={{ fromSecret "openshift-adp" "oadp-bucket" "AWS_SECRET_ACCESS_KEY" | base64dec }}
type: Opaque