apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-sample
  namespace: openshift-adp
spec:
  configuration:
    restic:
      enable: true 
  features:
    dataMover:
      enable: true
      credentialName: restic-credential