apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-install-oadp-backup
placementBindingDefaults:
  name: openshift-oadp-backup
policyDefaults:
  placement:
    placementRuleName: ocp-placementrule
  controls:
    - "CM-2 Baseline Configuration"
  pruneObjectBehavior: "DeleteIfCreated"
  namespace: global-policies
  remediationAction: enforce
  severity: medium
policies:
  - name: policy-oadp-backup
    manifests:
      - path: ./manifests-backup
