apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
spec:
  channel: 'stable-{{ (split "." ((lookup "cluster.open-cluster-management.io/v1alpha1" "ClusterClaim" "" "version.openshift.io").spec.value | print) )._0 }}.{{ (split "." ((lookup "cluster.open-cluster-management.io/v1alpha1" "ClusterClaim" "" "version.openshift.io").spec.value | print) )._1 }}'
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
